# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0653a59753a7d1a1e09819409981b036613b462664b0698c81597c16de11905c0e19df924edab9cb386a53c826be14c7b77ff9d1d2720f1f8b28baa2066a47fe

test:
  secret_key_base: b4d7fdb35fb0551c5501ae2aede76f561ddf1ff80eac18a13a448ebe1a9e025114d0866b779997c4c7e56b92c002fa278828b0a85fd157ad9baf40b24cdfae1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
